// Custom MapLibre style matching the "Waar is er zon?" brand palette.
// Uses OpenFreeMap's free vector tiles (OpenMapTiles schema).

const COLOR = {
  ink: '#1f2018',
  cream: '#fff4cf',
  paper: '#fff7db',
  moss: '#7ca857',
  mossSoft: '#cfe3a8',
  forest: '#315a48',
  sun: '#ffc341',
  sunSoft: '#ffe58d',
  blue: '#65c8e8',
  blueSoft: '#bfe8f4',
  road: '#fff7db',
  roadCasing: '#1f2018',
  building: '#f3e2a4',
  buildingOutline: 'rgba(31, 32, 24, 0.18)',
};

export const brandMapStyle = {
  version: 8,
  name: 'Waar is er zon',
  glyphs: 'https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf',
  sources: {
    openmaptiles: {
      type: 'vector',
      url: 'https://tiles.openfreemap.org/planet',
    },
  },
  layers: [
    {
      id: 'background',
      type: 'background',
      paint: { 'background-color': COLOR.cream },
    },
    {
      id: 'landcover-wood',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['==', 'class', 'wood'],
      paint: {
        'fill-color': COLOR.mossSoft,
        'fill-opacity': 0.55,
      },
    },
    {
      id: 'landcover-grass',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['in', 'class', 'grass', 'farmland'],
      paint: {
        'fill-color': COLOR.mossSoft,
        'fill-opacity': 0.35,
      },
    },
    {
      id: 'landcover-sand',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['==', 'class', 'sand'],
      paint: { 'fill-color': COLOR.sunSoft, 'fill-opacity': 0.55 },
    },
    {
      id: 'park',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'park',
      paint: {
        'fill-color': COLOR.mossSoft,
        'fill-opacity': 0.6,
      },
    },
    {
      id: 'park-outline',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'park',
      minzoom: 9,
      paint: {
        'line-color': COLOR.moss,
        'line-opacity': 0.5,
        'line-width': 1,
      },
    },
    {
      id: 'water',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'water',
      filter: ['!=', 'intermittent', 1],
      paint: {
        'fill-color': COLOR.blueSoft,
      },
    },
    {
      id: 'waterway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      paint: {
        'line-color': COLOR.blue,
        'line-width': ['interpolate', ['linear'], ['zoom'], 8, 0.6, 14, 2],
        'line-opacity': 0.7,
      },
    },
    {
      id: 'landuse-residential',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['==', 'class', 'residential'],
      minzoom: 10,
      paint: {
        'fill-color': COLOR.paper,
        'fill-opacity': 0.55,
      },
    },
    // Road casings (dark outline) — drawn first so the fill sits on top
    {
      id: 'road-casing-major',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['in', 'class', 'motorway', 'trunk', 'primary'],
      minzoom: 6,
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': COLOR.ink,
        'line-width': [
          'interpolate', ['linear'], ['zoom'],
          6, 0.8,
          10, 3,
          14, 7,
          18, 22,
        ],
      },
    },
    {
      id: 'road-casing-minor',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['in', 'class', 'secondary', 'tertiary', 'minor', 'street', 'service'],
      minzoom: 11,
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': COLOR.ink,
        'line-opacity': 0.55,
        'line-width': [
          'interpolate', ['linear'], ['zoom'],
          11, 0.5,
          14, 1.4,
          18, 8,
        ],
      },
    },
    // Road fills
    {
      id: 'road-motorway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['==', 'class', 'motorway'],
      minzoom: 6,
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': COLOR.sun,
        'line-width': [
          'interpolate', ['linear'], ['zoom'],
          6, 0.4,
          10, 2,
          14, 5,
          18, 18,
        ],
      },
    },
    {
      id: 'road-trunk-primary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['in', 'class', 'trunk', 'primary'],
      minzoom: 7,
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': COLOR.sunSoft,
        'line-width': [
          'interpolate', ['linear'], ['zoom'],
          7, 0.4,
          10, 1.6,
          14, 4,
          18, 16,
        ],
      },
    },
    {
      id: 'road-secondary-tertiary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['in', 'class', 'secondary', 'tertiary'],
      minzoom: 9,
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': COLOR.cream,
        'line-width': [
          'interpolate', ['linear'], ['zoom'],
          9, 0.4,
          14, 2.5,
          18, 12,
        ],
      },
    },
    {
      id: 'road-minor',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['in', 'class', 'minor', 'street', 'service'],
      minzoom: 12,
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': COLOR.cream,
        'line-width': [
          'interpolate', ['linear'], ['zoom'],
          12, 0.4,
          14, 1,
          18, 6,
        ],
      },
    },
    {
      id: 'building',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'building',
      minzoom: 13,
      paint: {
        'fill-color': COLOR.building,
        'fill-outline-color': COLOR.buildingOutline,
        'fill-opacity': [
          'interpolate', ['linear'], ['zoom'],
          13, 0,
          14, 0.85,
        ],
      },
    },
    {
      id: 'admin-country',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: ['all', ['<=', 'admin_level', 2], ['!=', 'maritime', 1]],
      paint: {
        'line-color': COLOR.ink,
        'line-width': ['interpolate', ['linear'], ['zoom'], 3, 0.8, 10, 2],
        'line-dasharray': [3, 2],
        'line-opacity': 0.55,
      },
    },
    {
      id: 'admin-region',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: ['all', ['==', 'admin_level', 4], ['!=', 'maritime', 1]],
      minzoom: 5,
      paint: {
        'line-color': COLOR.ink,
        'line-width': 0.6,
        'line-dasharray': [2, 2],
        'line-opacity': 0.3,
      },
    },
    {
      id: 'place-city',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', 'class', 'city'],
      layout: {
        'text-field': ['coalesce', ['get', 'name:nl'], ['get', 'name:latin'], ['get', 'name']],
        'text-font': ['Noto Sans Bold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 4, 11, 10, 16, 14, 22],
        'text-letter-spacing': 0.02,
        'text-transform': 'uppercase',
      },
      paint: {
        'text-color': COLOR.ink,
        'text-halo-color': COLOR.cream,
        'text-halo-width': 1.6,
      },
    },
    {
      id: 'place-town',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['in', 'class', 'town'],
      minzoom: 7,
      layout: {
        'text-field': ['coalesce', ['get', 'name:nl'], ['get', 'name:latin'], ['get', 'name']],
        'text-font': ['Noto Sans Bold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 7, 10, 14, 14],
      },
      paint: {
        'text-color': COLOR.ink,
        'text-halo-color': COLOR.cream,
        'text-halo-width': 1.4,
      },
    },
    {
      id: 'place-village',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['in', 'class', 'village', 'suburb', 'hamlet'],
      minzoom: 10,
      layout: {
        'text-field': ['coalesce', ['get', 'name:nl'], ['get', 'name:latin'], ['get', 'name']],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 10, 9, 14, 12],
      },
      paint: {
        'text-color': COLOR.ink,
        'text-halo-color': COLOR.cream,
        'text-halo-width': 1.2,
        'text-opacity': 0.85,
      },
    },
    {
      id: 'water-name',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'water_name',
      minzoom: 5,
      layout: {
        'text-field': ['coalesce', ['get', 'name:nl'], ['get', 'name:latin'], ['get', 'name']],
        'text-font': ['Noto Sans Italic'],
        'text-size': 11,
      },
      paint: {
        'text-color': '#3a8aa8',
        'text-halo-color': COLOR.blueSoft,
        'text-halo-width': 1.2,
      },
    },
  ],
};
